# Систолические массивы

![title](simple_array.png)

In [83]:
import numpy as np

def calc_array(A, B, ARRAY_W, ARRAY_L):
    res = np.zeros((ARRAY_W, ARRAY_W), dtype = np.int16)
    add = np.zeros((ARRAY_W, ARRAY_W + 2), dtype = np.int16)
    prop = np.zeros((ARRAY_W+2, ARRAY_L), dtype = np.int16)
    inp = np.zeros((ARRAY_W, ARRAY_W+2), dtype = np.int16)
    FETCH_LENGTH = ARRAY_L + ARRAY_W
    #A = np.transpose(A)
    
    param_data = B
    for k in range(FETCH_LENGTH):
        if (k > 0):
            u = min(ARRAY_W, k)
            for i in range(u):
                inp[i][u-i] = inp[i][u-i - 1]
        
        for i in range(ARRAY_W):
            if ((k - ARRAY_L <= i) and (i <= min(k, ARRAY_W-1)) and (k-i < ARRAY_L)):
                inp[i][0] = A[i][k-i]
            else:
                inp[i][0] = 0
#
        print(inp)
        print("-----")

        for i in range(ARRAY_W):
            for j in range(ARRAY_L):                
                if (i + j <= k):
                    res[i][j] = add[i][j] + B[i][j] * prop[i][j]
                    add[i][j + 1] = res[i][j]
        
    return res, add

In [84]:
ARRAY_W = 5 # Кол-во строк
ARRAY_L = 2 # Кол-во столбцов

A = B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]])
C, add = calc_array(A, B, ARRAY_W, ARRAY_L)
#print(C)
#print("-----------")
#print(add)

[[1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-----
[[2 1 0 0 0 0 0]
 [3 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-----
[[0 1 1 0 0 0 0]
 [4 3 0 0 0 0 0]
 [5 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-----
[[0 1 1 1 0 0 0]
 [0 3 3 0 0 0 0]
 [6 5 0 0 0 0 0]
 [7 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
-----
[[0 1 1 1 1 0 0]
 [0 3 3 3 0 0 0]
 [0 5 5 0 0 0 0]
 [8 7 0 0 0 0 0]
 [9 0 0 0 0 0 0]]
-----
[[ 0  1  1  1  1  1  0]
 [ 0  3  3  3  3  0  0]
 [ 0  5  5  5  0  0  0]
 [ 0  7  7  0  0  0  0]
 [10  9  0  0  0  0  0]]
-----
[[ 0  1  1  1  1  1  0]
 [ 0  3  3  3  3  0  0]
 [ 0  5  5  5  0  0  0]
 [ 0  7  7  0  0  0  0]
 [ 0 10  0  0  0  0  0]]
-----
