# Систолические массивы

![title](simple_array.png)

In [10]:
import numpy as np

def calc_array(A, B, ARRAY_W, ARRAY_L):
    res = np.zeros((ARRAY_W, ARRAY_W), dtype = np.int16)
    add = np.zeros((ARRAY_W + 1, ARRAY_W), dtype = np.int16)
    FETCH_LENGTH = ARRAY_L+ARRAY_W*2+1
    A = np.transpose(A)
    for i in range(FETCH_LENGTH):
        for j in range(min(cnt, ARRAY_L)):
            res[j, ARRAY_L - j] = 0 #TODO
    return res

In [11]:
ARRAY_W = 5 # Кол-во строк
ARRAY_L = 2 # Кол-во столбцов

A = B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]])
C = calc_array(A, B, ARRAY_W, ARRAY_L)
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
