# Систолические массивы

![title](simple_array.png)

In [14]:
import numpy as np

def calc_array(A, B, ARRAY_W, ARRAY_L):
    res = np.zeros((ARRAY_W, ARRAY_W), dtype = np.int16)
    add = np.zeros((ARRAY_W, ARRAY_W + 2), dtype = np.int16)
    prop = np.zeros((ARRAY_W + 2, ARRAY_L), dtype = np.int16)
    inp = np.zeros((ARRAY_W, ARRAY_W+2), dtype = np.int16)
    FETCH_LENGTH = 2 * ARRAY_L + ARRAY_W + 1
      
    param_data = B
    for k in range(FETCH_LENGTH):
        u = min(ARRAY_W, k) - 1
        for j in range(u + 1, -1, -1):
            for i in range(j):
                print(i, u - i + 1)
                inp[i][u - i + 1] = inp[i][u - i]
        
        for i in range(ARRAY_W):
            if ((k - ARRAY_L <= i) and (i <= min(k, ARRAY_W - 1)) and (k - i < ARRAY_L)):
                inp[i][0] = A[i][k - i]
            else:
                inp[i][0] = 0
        #print(inp)
        print("-----")

        for i in range(ARRAY_W):
            for j in range(ARRAY_L):                
                if (i + j <= k):
                    res[i][j] = add[i][j] + B[i][j] * prop[i][j]
                    add[i][j + 1] = res[i][j]
        
    return res, add

In [15]:
ARRAY_A_W = 5 # Кол-во столбцов
ARRAY_A_L = 2 # Кол-во строк

ARRAY_B_W = 2 # Кол-во столбцов
ARRAY_B_L = 5 # Кол-во строк

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]])
B = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]])
if (ARRAY_A_L == ARRAY_B_W):
    C, add = calc_array(A, B, ARRAY_W, ARRAY_L)
#print(C)
#print("-----------")
#print(add)

NameError: name 'ARRAY_W' is not defined

In [16]:
ARRAY_A_W = 5 # Кол-во строк
ARRAY_A_L = 3 # Кол-во столбцов

ARRAY_W_W = 3 # Кол-во строк
ARRAY_W_L = 4 # Кол-во столбцов

input_data = np.zeros((ARRAY_A_W, ARRAY_A_L))
for ii in range(ARRAY_A_W):
    for jj in range(ARRAY_A_L):
        input_data[ii][jj] = ARRAY_A_L*ii + jj + 1
print(input_data)

weight_data = np.zeros((ARRAY_W_W, ARRAY_W_L))
for ii in range(ARRAY_W_W):
    for jj in range(ARRAY_W_L):
        weight_data[ii][jj] = ARRAY_W_L*ii + jj + 1
print(weight_data)

print("A x W = ")
print(input_data.dot(weight_data))
print("-------------------------------")

input_data = np.zeros((ARRAY_A_W, ARRAY_A_L))
for ii in range(ARRAY_A_W):
    for jj in range(ARRAY_A_L):
        input_data[ii][jj] = ARRAY_A_L*jj + ii + 1
print(input_data)

weight_data = np.zeros((ARRAY_W_W, ARRAY_W_L))
for ii in range(ARRAY_W_W):
    for jj in range(ARRAY_W_L):
        weight_data[ii][jj] = ARRAY_W_L*ii + jj + 1
print(weight_data)

print("A1 x W = ")
print(input_data.dot(weight_data))
print("-------------------------------")

input_data = np.zeros((ARRAY_A_W, ARRAY_A_L))
for ii in range(ARRAY_A_W):
    for jj in range(ARRAY_A_L):
        input_data[ii][jj] = ARRAY_A_L*ii + jj + 1
print(input_data)

weight_data = np.zeros((ARRAY_W_W, ARRAY_W_L))
for ii in range(ARRAY_W_W):
    for jj in range(ARRAY_W_L):
        weight_data[ii][jj] = ARRAY_W_L*jj + ii + 1
print(weight_data)

print("A x W1 = ")
print(input_data.dot(weight_data))
print("-------------------------------")

input_data = np.zeros((ARRAY_A_W, ARRAY_A_L))
for ii in range(ARRAY_A_W):
    for jj in range(ARRAY_A_L):
        input_data[ii][jj] = ARRAY_A_L*jj + ii + 1
print(input_data)

weight_data = np.zeros((ARRAY_W_W, ARRAY_W_L))
for ii in range(ARRAY_W_W):
    for jj in range(ARRAY_W_L):
        weight_data[ii][jj] = ARRAY_W_L*jj + ii + 1
print(weight_data)

print("A1 x W1 = ")
print(input_data.dot(weight_data))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
A x W = 
[[ 38.  44.  50.  56.]
 [ 83.  98. 113. 128.]
 [128. 152. 176. 200.]
 [173. 206. 239. 272.]
 [218. 260. 302. 344.]]
-------------------------------
[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]
 [ 4.  7. 10.]
 [ 5.  8. 11.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
A1 x W = 
[[ 84.  96. 108. 120.]
 [ 99. 114. 129. 144.]
 [114. 132. 150. 168.]
 [129. 150. 171. 192.]
 [144. 168. 192. 216.]]
-------------------------------
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]]
A x W1 = 
[[ 14.  38.  62.  86.]
 [ 32.  92. 152. 212.]
 [ 50. 146. 242. 338.]
 [ 68. 200. 332. 464.]
 [ 86. 254. 422. 590.]]
-------------------------------
[[ 1.  4.  7.]
 [ 2.  5.  8.]
 [ 3.  6.  9.]
 [ 4.  7. 10.]
 [ 5.  8. 11.]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 1

In [126]:
ARRAY_A_W = 2
ARRAY_A_L = 5
min_a = min(ARRAY_A_L, ARRAY_A_W)
max_a = max(ARRAY_A_L, ARRAY_A_W)

for cnt in range(1, min_a + max_a + 10):
  if (cnt < min_a):
    print("stage 1_", cnt, ": ")
    for ii in range(0, cnt):
      print((cnt-ii-1, ii), end="")
    print()
  if ((cnt >= min_a) and (cnt < max_a + 1)):
    print("stage 2_", cnt, ": ")
    if (min_a == ARRAY_A_W):    
      for ii in range(0, min_a):
        print((min_a - ii - 1, cnt - min_a + ii), end="")
    else:
      for ii in range(0, min_a):
        print((cnt - ii - 1, ii), end="")
    print()
  if ((cnt > max_a) and (cnt < max_a + min_a)):
    print("stage 3_", cnt, ": ")
    for ii in range(0, max_a + min_a - cnt):
      print((ARRAY_A_W - ii - 1, ii - ARRAY_A_W + cnt), end="")
    print()

stage 1_ 1 : 
(0, 0)
stage 2_ 2 : 
(1, 0)(0, 1)
stage 2_ 3 : 
(1, 1)(0, 2)
stage 2_ 4 : 
(1, 2)(0, 3)
stage 2_ 5 : 
(1, 3)(0, 4)
stage 3_ 6 : 
(1, 4)


In [188]:
ARRAY_A_W = 9
ARRAY_A_L = ARRAY_W_W = 8
ARRAY_W_L = 15
FETCH_LENGTH = ARRAY_A_W + ARRAY_W_W + ARRAY_W_L + 1
min_a = min(ARRAY_A_L, ARRAY_A_W)
max_a = max(ARRAY_A_L, ARRAY_A_W)
min_a2 = min(ARRAY_W_L, ARRAY_A_W)
max_a2 = max(ARRAY_W_L, ARRAY_A_W)
print((min_a, max_a))
print((min_a2, max_a2))

for cnt in range(1, 1000):
  if ((cnt > ARRAY_A_L+1) and (cnt < ARRAY_A_L + min_a2 + 1)):
    print("stage 1_", cnt, ": ")
    for ii in range(0, cnt - ARRAY_A_L - 1):
      print((cnt - ARRAY_A_L-ii-2, ii), end="")
    print()
  if ((cnt >= ARRAY_A_L + min_a2 + 1) and (cnt <= FETCH_LENGTH - min_a2)):
    print("stage 2_", cnt, ": ")
    if (min_a2 == ARRAY_A_W):    
      for ii in range(0, min_a2):
        print((min_a2 - ii - 1, cnt - ARRAY_A_L - min_a2 + ii - 1), end="")
    else:
      for ii in range(0, min_a2):
        print((cnt - ARRAY_A_L - ii - 2, ii), end="")
    print()
  if ((cnt > FETCH_LENGTH - min_a2) and (cnt < FETCH_LENGTH)):
    print("stage 3_", cnt, ": ")
    for ii in range(0, FETCH_LENGTH - cnt):
      print((ARRAY_A_W - ii - 1, ii + cnt + ARRAY_W_L - FETCH_LENGTH), end="")
    print()

(8, 9)
(9, 15)
stage 1_ 10 : 
(0, 0)
stage 1_ 11 : 
(1, 0)(0, 1)
stage 1_ 12 : 
(2, 0)(1, 1)(0, 2)
stage 1_ 13 : 
(3, 0)(2, 1)(1, 2)(0, 3)
stage 1_ 14 : 
(4, 0)(3, 1)(2, 2)(1, 3)(0, 4)
stage 1_ 15 : 
(5, 0)(4, 1)(3, 2)(2, 3)(1, 4)(0, 5)
stage 1_ 16 : 
(6, 0)(5, 1)(4, 2)(3, 3)(2, 4)(1, 5)(0, 6)
stage 1_ 17 : 
(7, 0)(6, 1)(5, 2)(4, 3)(3, 4)(2, 5)(1, 6)(0, 7)
stage 2_ 18 : 
(8, 0)(7, 1)(6, 2)(5, 3)(4, 4)(3, 5)(2, 6)(1, 7)(0, 8)
stage 2_ 19 : 
(8, 1)(7, 2)(6, 3)(5, 4)(4, 5)(3, 6)(2, 7)(1, 8)(0, 9)
stage 2_ 20 : 
(8, 2)(7, 3)(6, 4)(5, 5)(4, 6)(3, 7)(2, 8)(1, 9)(0, 10)
stage 2_ 21 : 
(8, 3)(7, 4)(6, 5)(5, 6)(4, 7)(3, 8)(2, 9)(1, 10)(0, 11)
stage 2_ 22 : 
(8, 4)(7, 5)(6, 6)(5, 7)(4, 8)(3, 9)(2, 10)(1, 11)(0, 12)
stage 2_ 23 : 
(8, 5)(7, 6)(6, 7)(5, 8)(4, 9)(3, 10)(2, 11)(1, 12)(0, 13)
stage 2_ 24 : 
(8, 6)(7, 7)(6, 8)(5, 9)(4, 10)(3, 11)(2, 12)(1, 13)(0, 14)
stage 3_ 25 : 
(8, 7)(7, 8)(6, 9)(5, 10)(4, 11)(3, 12)(2, 13)(1, 14)
stage 3_ 26 : 
(8, 8)(7, 9)(6, 10)(5, 11)(4, 12)(3, 13)(2, 14)
stag