# Систолические массивы

![title](simple_array.png)

In [55]:
import numpy as np

def calc_array(A, B, ARRAY_W, ARRAY_L):
    res = np.zeros((ARRAY_W, ARRAY_W), dtype = np.int16)
    add = np.zeros((ARRAY_W, ARRAY_W + 2), dtype = np.int16)
    prop = np.zeros((ARRAY_W, ARRAY_W), dtype = np.int16)
    FETCH_LENGTH = ARRAY_L + ARRAY_W
    #A = np.transpose(A)
    
    param_data = B
    for k in range(FETCH_LENGTH):
        if (k > 0):
            for i in range(ARRAY_W):
                for j in range(ARRAY_W):
                    prop[i][j + 1] = prop[i][j]

        for i in range(ARRAY_W):
            for j in range(ARRAY_L):
                if (i + j == k):
                    prop[i][0] = A[i][j]

        print(prop)
        print("-----")

        for i in range(ARRAY_W):
            for j in range(ARRAY_W):                
                if (i + j <= k):
                    res[i][j] = add[i][j] + B[i][j] * prop[i][j]
                    add[i][j + 1] = res[i][j]
        
    return res, add

In [56]:
ARRAY_W = 5 # Кол-во строк
ARRAY_L = 2 # Кол-во столбцов

A = B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]])
C, add = calc_array(A, B, ARRAY_W, ARRAY_L)
#print(C)
#print("-----------")
#print(add)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
-----


IndexError: index 5 is out of bounds for axis 0 with size 5